<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/10
 * Time: 10:08
 */
namespace app\mobile\controller;

class Detail extends Base {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $id = input('get.name/name');
        $data = db('news')->where("id",$id)->field('id,title,subtitle,source,writer,time,content')->select();
        $data[0]['content'] = str_replace('upload','/upload',$data[0]['content']);
	$data[0]['content'] = str_replace('img src','img style="max-width:95%;height:auto;margin: 0 auto;display: block;" src',$data[0]['content']);
        $this->assign('data',$data);
        return $this->fetch();
    }
    //上下页方法
    public function done(){
        if(request()->isAjax()){
            $type = input("post.type");
            $id = input("post.id");
            if($type=="prev"){
                return $this->selectnews($id,"-1");
            }elseif ($type=="next"){
                return $this->selectnews($id,"1");
            }
        }else{
            return "error";
        }
    }
    //查询上或下一条新闻，$no +1为下一篇，-1为上一篇
    public function selectnews($id,$no){
        $where = db('news')->field("type")->where('id',$id)->find();
        $data =  db("news")->order("time desc")->where($where)->select();
        foreach ($data as $k => $val){
            if($id == $val['Id']){
                $num = $k +$no ;
            }
        }
        if($num>=0&&$num<count($data)){
            $data[$num]['content'] = str_replace('upload','/upload',$data[$num]['content']);
$data[$num]['content'] = str_replace('img src','img style="max-width:95%;height:auto;margin: 0 auto;display: block;" src',$data[$num]['content']);
            return $data[$num];
        }else{
            return "false";
        }
    }
}