<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/7
 * Time: 17:09
 */
namespace app\mobile\controller;
use think\db;
class Index extends Base {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $newsdata = db('news')->limit('4')->order('time desc')->field('id,title')->where('type = 2')->select();
        $this->assign('newsdata',$newsdata);
        return $this->fetch();
    }
}