<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/9/10
 * Time: 10:08
 */
namespace app\mobile\controller;
use think\db;

class News extends Base {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        if(request()->isAjax()){
            $type = input('post.type');
            if($type==1){
                $data = $this->selectnews(1);
                return json($data);
            }elseif($type==2){
                $data = $this->selectnews(2);
                return json($data);
            }
            else{
                echo "error";
            }
        }
        $data = $this->selectnews(1);
        $this->assign('data',$data);
        return $this->fetch();
    }

    public function selectnews($type){
        $data = db('news')->field('id,png_id,bg_id,title,subtitle,time')->order('time desc')->where('type',$type )->select();
        $img = db('picture')->field('id,name')->where('belong','news')->select();
        foreach ($img as $k => $arr){
            $brr[$arr['id']] =$arr;
        }
        foreach ($data as $k => $crr){
            $imgid = $crr['png_id'];
            $data[$k]['imgname'] = $brr[$imgid];
        }
        return $data;
    }
}